(define (pascal-elements n)
  (define (pascal-elements-iter n count)
    (define (pascal-row i)
      (define (pascal-row-iter i j)
        (define (pascal i j)
          (cond ((and (= i 0)(= j 0)) 1)
                ((or (< j 0) (> j (+ i 1))) 0)
                (else (+ (pascal(- i 1) (- j 1)) (pascal(- i 1) j)))))
        (display (pascal i j))
        (display " ")
        (if (> j 0)
            (pascal-row-iter i (- j 1) ))) 
      (pascal-row-iter i i)
      (newline))
    (pascal-row (- n count))
    (if (> count 0)
        (pascal-elements-iter n (- count 1))))
  (pascal-elements-iter n n))

                 
(pascal-elements 4) 
